### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Anviksha-Sharma** [kamalsairajk/Gator-X#31]
- [x] Description of your application - 200 words max
- [x] Demo video functionality - 3min max
- [x] Cypress test video - 90sec max
- [x] Backend unit test video - 90sec max
- [x] Link to API Documentation
- [x] Link to Project board
- [x] Link to Sprint4 deliverables
- [x] Frontend and backend team members

**Comment by siddharth-upadhyayula** [comment]
Final Changes are done
